-- Sales Rep Override Commissions
-- Allows senior/manager reps to earn a percentage of gross revenue
-- generated by subordinate reps assigned under them.

-- Override assignment: links a senior rep to a subordinate rep with a configurable override rate
CREATE TABLE "SalesRepOverrideAssignment" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "clinicId" INTEGER NOT NULL,
    "overrideRepId" INTEGER NOT NULL,
    "subordinateRepId" INTEGER NOT NULL,
    "overridePercentBps" INTEGER NOT NULL,
    "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "effectiveTo" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "assignedById" INTEGER,
    "notes" TEXT,

    CONSTRAINT "SalesRepOverrideAssignment_pkey" PRIMARY KEY ("id")
);

-- Override commission event ledger
CREATE TABLE "SalesRepOverrideCommissionEvent" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "clinicId" INTEGER NOT NULL,
    "overrideRepId" INTEGER NOT NULL,
    "subordinateRepId" INTEGER NOT NULL,
    "sourceCommissionEventId" INTEGER,
    "overrideAssignmentId" INTEGER NOT NULL,
    "eventAmountCents" INTEGER NOT NULL,
    "overridePercentBps" INTEGER NOT NULL,
    "commissionAmountCents" INTEGER NOT NULL,
    "patientId" INTEGER,
    "stripeEventId" TEXT,
    "status" "CommissionEventStatus" NOT NULL DEFAULT 'PENDING',
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "holdUntil" TIMESTAMP(3),
    "approvedAt" TIMESTAMP(3),
    "paidAt" TIMESTAMP(3),
    "reversedAt" TIMESTAMP(3),
    "reversalReason" TEXT,
    "isManual" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "metadata" JSONB,

    CONSTRAINT "SalesRepOverrideCommissionEvent_pkey" PRIMARY KEY ("id")
);

-- Unique constraints
CREATE UNIQUE INDEX "SalesRepOverrideAssignment_clinicId_overrideRepId_subordinat_key"
    ON "SalesRepOverrideAssignment"("clinicId", "overrideRepId", "subordinateRepId");

CREATE UNIQUE INDEX "SalesRepOverrideCommissionEvent_clinicId_stripeEventId_overr_key"
    ON "SalesRepOverrideCommissionEvent"("clinicId", "stripeEventId", "overrideRepId");

-- Indexes for SalesRepOverrideAssignment
CREATE INDEX "SalesRepOverrideAssignment_clinicId_idx"
    ON "SalesRepOverrideAssignment"("clinicId");
CREATE INDEX "SalesRepOverrideAssignment_overrideRepId_idx"
    ON "SalesRepOverrideAssignment"("overrideRepId");
CREATE INDEX "SalesRepOverrideAssignment_subordinateRepId_idx"
    ON "SalesRepOverrideAssignment"("subordinateRepId");
CREATE INDEX "SalesRepOverrideAssignment_isActive_idx"
    ON "SalesRepOverrideAssignment"("isActive");

-- Indexes for SalesRepOverrideCommissionEvent
CREATE INDEX "SalesRepOverrideCommissionEvent_overrideRepId_status_idx"
    ON "SalesRepOverrideCommissionEvent"("overrideRepId", "status");
CREATE INDEX "SalesRepOverrideCommissionEvent_clinicId_occurredAt_idx"
    ON "SalesRepOverrideCommissionEvent"("clinicId", "occurredAt");
CREATE INDEX "SalesRepOverrideCommissionEvent_subordinateRepId_occurredAt_idx"
    ON "SalesRepOverrideCommissionEvent"("subordinateRepId", "occurredAt");
CREATE INDEX "SalesRepOverrideCommissionEvent_sourceCommissionEventId_idx"
    ON "SalesRepOverrideCommissionEvent"("sourceCommissionEventId");

-- Foreign keys for SalesRepOverrideAssignment
ALTER TABLE "SalesRepOverrideAssignment"
    ADD CONSTRAINT "SalesRepOverrideAssignment_clinicId_fkey"
    FOREIGN KEY ("clinicId") REFERENCES "Clinic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "SalesRepOverrideAssignment"
    ADD CONSTRAINT "SalesRepOverrideAssignment_overrideRepId_fkey"
    FOREIGN KEY ("overrideRepId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "SalesRepOverrideAssignment"
    ADD CONSTRAINT "SalesRepOverrideAssignment_subordinateRepId_fkey"
    FOREIGN KEY ("subordinateRepId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Foreign keys for SalesRepOverrideCommissionEvent
ALTER TABLE "SalesRepOverrideCommissionEvent"
    ADD CONSTRAINT "SalesRepOverrideCommissionEvent_clinicId_fkey"
    FOREIGN KEY ("clinicId") REFERENCES "Clinic"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "SalesRepOverrideCommissionEvent"
    ADD CONSTRAINT "SalesRepOverrideCommissionEvent_overrideRepId_fkey"
    FOREIGN KEY ("overrideRepId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "SalesRepOverrideCommissionEvent"
    ADD CONSTRAINT "SalesRepOverrideCommissionEvent_overrideAssignmentId_fkey"
    FOREIGN KEY ("overrideAssignmentId") REFERENCES "SalesRepOverrideAssignment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
