/**
 * Weight Loss Intake Form — Ported from eonmeds/weightlossintake
 *
 * This is the first template in the platform's template library.
 * It mirrors the 40+ step eonmeds intake with conditional navigation,
 * bilingual content (EN/ES), and custom step component references.
 *
 * Stored as FormConfig JSON in IntakeFormTemplate.metadata.formConfig.
 */

import type { FormConfig, FormStep } from '../types/form-engine';

const steps: FormStep[] = [
  // ===== SECTION 1: ONBOARDING =====
  {
    id: 'goals',
    path: 'goals',
    title: { en: 'How would your life change by losing weight?', es: '¿Cómo cambiaría tu vida al perder peso?' },
    subtitle: { en: 'Select all that apply.', es: 'Selecciona todos los que apliquen.' },
    type: 'multi-select',
    fields: [{
      id: 'goals', type: 'checkbox',
      label: { en: 'Goals', es: 'Objetivos' },
      storageKey: 'goals',
      options: [
        { id: 'clothes', label: { en: 'Enjoy how your clothes fit', es: 'Disfrutar cómo te queda la ropa' }, value: 'clothes' },
        { id: 'confidence', label: { en: 'Having more confidence', es: 'Tener más confianza' }, value: 'confidence' },
        { id: 'energy', label: { en: 'Getting your energy back', es: 'Recuperar tu energía' }, value: 'energy' },
        { id: 'feel_better', label: { en: 'Feel better about yourself', es: 'Sentirte mejor contigo mismo' }, value: 'feel_better' },
        { id: 'health', label: { en: 'Improving your overall health', es: 'Mejorar tu salud general' }, value: 'health' },
      ],
      validation: [{ type: 'required', message: { en: 'Please select at least one goal', es: 'Por favor selecciona al menos un objetivo' } }],
    }],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'medication-preference',
    prevStep: null,
    progressPercent: 3,
  },
  {
    id: 'medication-preference',
    path: 'medication-preference',
    title: { en: 'Do you have a specific weight loss medication in mind?', es: '¿Tienes en mente algún medicamento específico para perder peso?' },
    type: 'single-select',
    fields: [{
      id: 'medication_preference', type: 'radio',
      label: { en: 'Preference', es: 'Preferencia' },
      storageKey: 'medication_preference',
      options: [
        { id: 'recommendation', label: { en: "Not yet, I'm looking for a recommendation", es: 'Todavía no, busco una recomendación' }, value: 'recommendation' },
        { id: 'have_in_mind', label: { en: 'Yes, I already have something in mind', es: 'Sí, ya tengo algo en mente' }, value: 'have_in_mind' },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'consent',
    prevStep: 'goals',
    progressPercent: 6,
  },

  // ===== SECTION 2: CONSENT & BASIC INFO =====
  {
    id: 'consent',
    path: 'consent',
    title: { en: 'This questionnaire helps us understand your medical history, lifestyle, and goals.', es: 'Este cuestionario nos ayuda a entender tu historial médico, estilo de vida y objetivos.' },
    subtitle: { en: 'Your responses are private and will be reviewed by our medical team.', es: 'Tus respuestas son privadas y serán revisadas por nuestro equipo médico.' },
    type: 'custom',
    component: 'ConsentStep',
    fields: [{
      id: 'consent_accepted', type: 'checkbox',
      label: { en: 'I understand and agree', es: 'Entiendo y acepto' },
      storageKey: 'consent_accepted',
      validation: [{ type: 'required', message: { en: 'You must accept to continue', es: 'Debes aceptar para continuar' } }],
    }],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'state',
    prevStep: 'medication-preference',
    progressPercent: 8,
  },
  {
    id: 'state',
    path: 'state',
    title: { en: 'Select the state you live in:', es: 'Selecciona el estado en el que vives:' },
    subtitle: { en: 'This state is where your medication will be shipped to, if prescribed.', es: 'Este estado es donde se enviará tu medicamento, si se receta.' },
    type: 'input',
    fields: [
      {
        id: 'state', type: 'select',
        label: { en: 'State', es: 'Estado' },
        storageKey: 'state',
        validation: [{ type: 'required', message: { en: 'Please select a state', es: 'Por favor selecciona un estado' } }],
      },
      {
        id: 'terms_accepted', type: 'checkbox',
        label: { en: 'I agree to the Terms and Conditions and Privacy Policy', es: 'Acepto los Términos y Condiciones y la Política de Privacidad' },
        storageKey: 'terms_accepted',
        validation: [{ type: 'required', message: { en: 'You must accept the terms', es: 'Debes aceptar los términos' } }],
      },
    ],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'name',
    prevStep: 'consent',
    progressPercent: 10,
  },
  {
    id: 'name',
    path: 'name',
    title: { en: 'What is your name?', es: '¿Cuál es tu nombre?' },
    subtitle: { en: 'This way, we can personalize your experience.', es: 'De esta manera, podemos personalizar tu experiencia.' },
    type: 'input',
    fields: [
      { id: 'firstName', type: 'text', label: { en: 'First Name', es: 'Nombre' }, placeholder: { en: 'First Name', es: 'Nombre' }, storageKey: 'firstName', validation: [{ type: 'required', message: { en: 'First name is required', es: 'El nombre es requerido' } }] },
      { id: 'lastName', type: 'text', label: { en: 'Last Name', es: 'Apellido' }, placeholder: { en: 'Last Name', es: 'Apellido' }, storageKey: 'lastName', validation: [{ type: 'required', message: { en: 'Last name is required', es: 'El apellido es requerido' } }] },
    ],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'dob',
    prevStep: 'state',
    progressPercent: 12,
  },
  {
    id: 'dob',
    path: 'dob',
    title: { en: 'To check if you qualify, tell us your date of birth.', es: 'Para verificar si calificas, dinos tu fecha de nacimiento.' },
    type: 'input',
    fields: [{
      id: 'dob', type: 'date',
      label: { en: 'Date of Birth', es: 'Fecha de Nacimiento' },
      placeholder: { en: 'MM/DD/YYYY', es: 'MM/DD/AAAA' },
      storageKey: 'dob',
      validation: [
        { type: 'required', message: { en: 'Date of birth is required', es: 'La fecha de nacimiento es requerida' } },
        { type: 'age', value: 18, message: { en: 'You must be at least 18 years old', es: 'Debes tener al menos 18 años' } },
      ],
    }],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'sex-assigned',
    prevStep: 'name',
    progressPercent: 14,
  },
  {
    id: 'sex-assigned',
    path: 'sex-assigned',
    title: { en: 'Sex assigned at birth', es: 'Sexo asignado al nacer' },
    type: 'single-select',
    fields: [{
      id: 'sex', type: 'radio',
      label: { en: 'Sex', es: 'Sexo' },
      storageKey: 'sex',
      options: [
        { id: 'male', label: { en: 'Male', es: 'Hombre' }, value: 'male' },
        { id: 'female', label: { en: 'Female', es: 'Mujer' }, value: 'female' },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'contact-info',
    prevStep: 'dob',
    progressPercent: 16,
  },
  {
    id: 'contact-info',
    path: 'contact-info',
    title: { en: 'How can we reach you?', es: '¿Cómo podemos contactarte?' },
    type: 'input',
    fields: [
      { id: 'email', type: 'email', label: { en: 'Email', es: 'Correo electrónico' }, placeholder: { en: 'your@email.com', es: 'tu@email.com' }, storageKey: 'email', validation: [{ type: 'required', message: { en: 'Email is required', es: 'El correo electrónico es requerido' } }, { type: 'email', message: { en: 'Please enter a valid email', es: 'Por favor ingresa un correo válido' } }] },
      { id: 'phone', type: 'phone', label: { en: 'Phone number', es: 'Número de teléfono' }, placeholder: { en: '(555) 555-5555', es: '(555) 555-5555' }, storageKey: 'phone', validation: [{ type: 'required', message: { en: 'Phone number is required', es: 'El número de teléfono es requerido' } }, { type: 'phone', message: { en: 'Please enter a valid phone number', es: 'Por favor ingresa un número válido' } }] },
    ],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'address',
    prevStep: 'sex-assigned',
    progressPercent: 18,
  },

  // ===== SECTION 3: ADDRESS & WEIGHT =====
  {
    id: 'address',
    path: 'address',
    title: { en: "What's your shipping address?", es: '¿Cuál es tu dirección de envío?' },
    subtitle: { en: 'All treatment medications are shipped to your door.', es: 'Todos los medicamentos de tratamiento se envían a tu puerta.' },
    type: 'input',
    fields: [
      { id: 'street', type: 'text', label: { en: 'Street Address', es: 'Dirección' }, storageKey: 'street', validation: [{ type: 'required', message: { en: 'Address is required', es: 'La dirección es requerida' } }] },
      { id: 'apartment', type: 'text', label: { en: 'Apartment/Suite (Optional)', es: 'Apartamento/Suite (Opcional)' }, storageKey: 'apartment' },
    ],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'ideal-weight',
    prevStep: 'contact-info',
    progressPercent: 25,
  },
  {
    id: 'ideal-weight',
    path: 'ideal-weight',
    title: { en: "What's your ideal weight?", es: '¿Cuál es tu peso ideal?' },
    type: 'input',
    fields: [{ id: 'ideal_weight', type: 'number', label: { en: 'Ideal Weight (lbs)', es: 'Peso Ideal (lbs)' }, storageKey: 'ideal_weight', validation: [{ type: 'required', message: { en: 'Please enter your ideal weight', es: 'Por favor ingresa tu peso ideal' } }] }],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'current-weight',
    prevStep: 'address',
    progressPercent: 30,
  },
  {
    id: 'current-weight',
    path: 'current-weight',
    title: { en: "What's your current weight?", es: '¿Cuál es tu peso actual?' },
    type: 'input',
    fields: [
      { id: 'current_weight', type: 'number', label: { en: 'Current Weight (lbs)', es: 'Peso Actual (lbs)' }, storageKey: 'current_weight', validation: [{ type: 'required', message: { en: 'Please enter your weight', es: 'Por favor ingresa tu peso' } }] },
      { id: 'height_feet', type: 'select', label: { en: 'Height (feet)', es: 'Altura (pies)' }, storageKey: 'height_feet', validation: [{ type: 'required', message: { en: 'Please select feet', es: 'Por favor selecciona pies' } }] },
      { id: 'height_inches', type: 'select', label: { en: 'Height (inches)', es: 'Altura (pulgadas)' }, storageKey: 'height_inches', validation: [{ type: 'required', message: { en: 'Please select inches', es: 'Por favor selecciona pulgadas' } }] },
    ],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'medical-history',
    prevStep: 'ideal-weight',
    progressPercent: 35,
  },

  // ===== SECTION 4: MEDICAL HISTORY =====
  {
    id: 'medical-history',
    path: 'medical-history',
    title: { en: "Now let's review your medical history.", es: 'Ahora revisemos tu historial médico.' },
    type: 'info',
    fields: [],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: [
      { conditions: [{ field: 'sex', operator: 'equals', value: 'female' }], target: 'pregnancy' },
      { conditions: [{ field: 'sex', operator: 'equals', value: 'male' }], target: 'activity-level' },
    ],
    prevStep: 'current-weight',
    progressPercent: 40,
  },
  {
    id: 'pregnancy',
    path: 'pregnancy',
    title: { en: 'Are you currently pregnant, breastfeeding, or planning to become pregnant in the next 6 months?', es: '¿Estás actualmente embarazada, amamantando o planeas quedar embarazada en los próximos 6 meses?' },
    type: 'single-select',
    fields: [{
      id: 'pregnancy_status', type: 'radio',
      label: { en: 'Pregnancy Status', es: 'Estado de Embarazo' },
      storageKey: 'pregnancy_status',
      options: [
        { id: 'yes', label: { en: 'Yes', es: 'Sí' }, value: 'yes' },
        { id: 'no', label: { en: 'No', es: 'No' }, value: 'no' },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'activity-level',
    prevStep: 'medical-history',
    progressPercent: 42,
  },
  {
    id: 'activity-level',
    path: 'activity-level',
    title: { en: 'What is your usual level of daily physical activity?', es: '¿Cuál es tu nivel habitual de actividad física diaria?' },
    type: 'single-select',
    fields: [{
      id: 'activity_level', type: 'radio',
      label: { en: 'Activity Level', es: 'Nivel de Actividad' },
      storageKey: 'activity_level',
      options: [
        { id: '5', label: { en: '5 - Very Active', es: '5 - Muy Activo' }, value: '5', description: { en: 'Exercise 5 to 7 times per week', es: 'Ejercicio 5 a 7 veces por semana' } },
        { id: '3', label: { en: '3 - Moderately Active', es: '3 - Moderadamente Activo' }, value: '3', description: { en: 'Exercise 3 to 4 times per week', es: 'Ejercicio 3 a 4 veces por semana' } },
        { id: '1', label: { en: '1 - Not very active', es: '1 - No soy muy activo' }, value: '1', description: { en: "Usually don't exercise", es: 'Usualmente no hago ejercicio' } },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'chronic-conditions',
    prevStep: 'medical-history',
    progressPercent: 50,
  },
  {
    id: 'chronic-conditions',
    path: 'chronic-conditions',
    title: { en: 'Do you have any medical conditions or chronic diseases?', es: '¿Tienes alguna condición médica o enfermedad crónica?' },
    type: 'single-select',
    fields: [{
      id: 'has_chronic_conditions', type: 'radio',
      label: { en: 'Chronic Conditions', es: 'Condiciones Crónicas' },
      storageKey: 'has_chronic_conditions',
      options: [
        { id: 'yes', label: { en: 'Yes', es: 'Sí' }, value: 'yes' },
        { id: 'no', label: { en: 'No', es: 'No' }, value: 'no' },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'glp1-history',
    prevStep: 'activity-level',
    progressPercent: 60,
  },

  // ===== SECTION 5: GLP-1 HISTORY =====
  {
    id: 'glp1-history',
    path: 'glp1-history',
    title: { en: 'Do you currently take or have you ever taken a GLP-1 medication for weight loss?', es: '¿Actualmente toma o ha tomado alguna vez un medicamento GLP-1 para perder peso?' },
    subtitle: { en: 'GLP-1s include compounded semaglutide, compounded tirzepatide, Ozempic, Wegovy, Mounjaro or Zepbound', es: 'Los GLP-1 incluyen semaglutida compuesta, tirzepatida compuesta, Ozempic, Wegovy, Mounjaro o Zepbound' },
    type: 'single-select',
    fields: [{
      id: 'glp1_history', type: 'radio',
      label: { en: 'GLP-1 History', es: 'Historial GLP-1' },
      storageKey: 'glp1_history',
      options: [
        { id: 'currently_taking', label: { en: 'Yes, I am currently taking a GLP-1', es: 'Sí, actualmente estoy tomando un GLP-1' }, value: 'currently_taking' },
        { id: 'previously_taken', label: { en: 'Yes, I have taken a GLP-1 before but not currently', es: 'Sí, he tomado un GLP-1 antes pero no actualmente' }, value: 'previously_taken' },
        { id: 'never_taken', label: { en: 'No, I have never taken a GLP-1', es: 'No, nunca he tomado un GLP-1' }, value: 'never_taken' },
        { id: 'considering', label: { en: 'No, but I am considering it', es: 'No, pero lo estoy considerando' }, value: 'considering' },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'blood-pressure',
    prevStep: 'chronic-conditions',
    progressPercent: 70,
  },

  // ===== SECTION 6: REMAINING MEDICAL =====
  {
    id: 'blood-pressure',
    path: 'blood-pressure',
    title: { en: "What's your most recent blood pressure reading?", es: '¿Cuál es tu lectura de presión arterial más reciente?' },
    type: 'single-select',
    fields: [{
      id: 'blood_pressure', type: 'radio',
      label: { en: 'Blood Pressure', es: 'Presión Arterial' },
      storageKey: 'blood_pressure',
      options: [
        { id: 'normal', label: { en: 'Normal (below 120/80 mmHg)', es: 'Normal (menos de 120/80 mmHg)' }, value: 'normal' },
        { id: 'elevated', label: { en: 'Elevated (120-129/less than 80 mmHg)', es: 'Elevada (120-129/menos de 80 mmHg)' }, value: 'elevated' },
        { id: 'high', label: { en: 'High Blood Pressure (130/80 mmHg or higher)', es: 'Presión Alta (130/80 mmHg o más)' }, value: 'high' },
        { id: 'unknown', label: { en: "I don't know", es: 'No lo sé' }, value: 'unknown' },
      ],
    }],
    autoAdvance: true,
    showContinueButton: false,
    nextStep: 'allergies',
    prevStep: 'glp1-history',
    progressPercent: 80,
  },
  {
    id: 'allergies',
    path: 'allergies',
    title: { en: 'Do you have any known allergies to medications?', es: '¿Tienes alguna alergia conocida a medicamentos?' },
    type: 'input',
    fields: [{
      id: 'allergies', type: 'textarea',
      label: { en: 'List any medication allergies', es: 'Lista cualquier alergia a medicamentos' },
      placeholder: { en: 'Type "none" if no allergies', es: 'Escribe "ninguna" si no tienes alergias' },
      storageKey: 'allergies',
      validation: [{ type: 'required', message: { en: 'Please respond to this question', es: 'Por favor responde a esta pregunta' } }],
    }],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'additional-info',
    prevStep: 'blood-pressure',
    progressPercent: 85,
  },
  {
    id: 'additional-info',
    path: 'additional-info',
    title: { en: 'Anything else you would like your provider to know?', es: '¿Algo más que quieras que tu proveedor sepa?' },
    type: 'input',
    fields: [{
      id: 'additional_info', type: 'textarea',
      label: { en: 'Additional information', es: 'Información adicional' },
      placeholder: { en: 'Optional', es: 'Opcional' },
      storageKey: 'additional_info',
    }],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'review',
    prevStep: 'allergies',
    progressPercent: 90,
  },

  // ===== SECTION 7: REVIEW & SUBMIT =====
  {
    id: 'review',
    path: 'review',
    title: { en: 'Review your information', es: 'Revisa tu información' },
    subtitle: { en: 'Please verify the information below before submitting.', es: 'Por favor verifica la información antes de enviar.' },
    type: 'custom',
    component: 'ReviewStep',
    fields: [],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: 'qualified',
    prevStep: 'additional-info',
    progressPercent: 95,
  },
  {
    id: 'qualified',
    path: 'qualified',
    title: { en: 'Great news!', es: '¡Excelentes noticias!' },
    subtitle: { en: 'Based on your responses, you may qualify for treatment. A licensed provider will review your information.', es: 'Según tus respuestas, puedes calificar para el tratamiento. Un proveedor licenciado revisará tu información.' },
    type: 'custom',
    component: 'QualifiedStep',
    fields: [],
    autoAdvance: false,
    showContinueButton: true,
    nextStep: null,
    prevStep: 'review',
    progressPercent: 100,
  },
];

export const weightLossIntakeConfig: FormConfig = {
  id: 'weight-loss-intake',
  name: 'Weight Loss Medical Intake',
  version: '2.0.0',
  description: 'Comprehensive medical intake questionnaire for weight loss programs with GLP-1 medication assessment',
  treatmentType: 'weight-loss',
  steps,
  startStep: 'goals',
  languages: ['en', 'es'],
  defaultLanguage: 'en',
  integrations: [
    { type: 'platform', triggers: ['complete'] },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
