/**
 * Treatment-based feature presets for the patient portal.
 * Apply a preset to set recommended feature flags for a clinic (e.g. at create or via "Apply preset" in admin).
 * Merge with existing features; preset only sets keys it defines.
 */

import type { PortalTreatmentType, PortalFeatureFlagKey } from './types';

export type PortalFeaturePreset = Partial<Record<PortalFeatureFlagKey, boolean>>;

/** Recommended feature flags per treatment type (partial; unset keys leave existing value) */
export const TREATMENT_PRESETS: Record<PortalTreatmentType, PortalFeaturePreset> = {
  weight_loss: {
    showWeightTracking: true,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: true,
    showHealthScore: true,
    showAchievements: true,
    showBMICalculator: true,
    showCalorieCalculator: true,
    showDoseCalculator: true,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showLabResults: false,
    showTelehealth: false,
    showCommunityChat: false,
  },
  hormone_therapy: {
    showWeightTracking: true,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: false,
    showHealthScore: true,
    showAchievements: true,
    showLabResults: true,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showBMICalculator: true,
    showCalorieCalculator: false,
    showDoseCalculator: false,
    showTelehealth: false,
    showCommunityChat: false,
  },
  mens_health: {
    showWeightTracking: true,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: false,
    showHealthScore: true,
    showAchievements: true,
    showLabResults: true,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showBMICalculator: true,
    showCalorieCalculator: true,
    showDoseCalculator: false,
    showTelehealth: false,
    showCommunityChat: false,
  },
  womens_health: {
    showWeightTracking: true,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: false,
    showHealthScore: true,
    showAchievements: true,
    showLabResults: true,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showBMICalculator: true,
    showCalorieCalculator: true,
    showDoseCalculator: false,
    showTelehealth: false,
    showCommunityChat: false,
  },
  sexual_health: {
    showWeightTracking: false,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: false,
    showHealthScore: true,
    showAchievements: false,
    showLabResults: true,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showBMICalculator: true,
    showCalorieCalculator: false,
    showDoseCalculator: false,
    showTelehealth: true,
    showCommunityChat: false,
  },
  anti_aging: {
    showWeightTracking: true,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: false,
    showHealthScore: true,
    showAchievements: true,
    showLabResults: true,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showBMICalculator: true,
    showCalorieCalculator: true,
    showDoseCalculator: false,
    showTelehealth: false,
    showCommunityChat: false,
  },
  general_wellness: {
    showWeightTracking: true,
    showWaterTracking: true,
    showExerciseTracking: true,
    showSleepTracking: true,
    showDietaryPlans: true,
    showProgressPhotos: false,
    showHealthScore: true,
    showAchievements: true,
    showLabResults: false,
    showSymptomChecker: true,
    showAppointments: true,
    showCarePlan: true,
    showCareTeam: true,
    showChat: true,
    showResources: true,
    showShipmentTracking: true,
    showMedicationReminders: true,
    showBilling: true,
    showBMICalculator: true,
    showCalorieCalculator: true,
    showDoseCalculator: false,
    showTelehealth: false,
    showCommunityChat: false,
  },
  custom: {
    // No override; clinic configures manually
  },
};

/** Human-readable labels for treatment types (for admin dropdown) */
export const TREATMENT_PRESET_LABELS: Record<PortalTreatmentType, string> = {
  weight_loss: 'Weight loss (GLP-1, etc.)',
  hormone_therapy: 'Hormone therapy',
  mens_health: "Men's health",
  womens_health: "Women's health",
  sexual_health: 'Sexual health',
  anti_aging: 'Anti-aging',
  general_wellness: 'General wellness',
  custom: 'Custom (no preset)',
};

/**
 * Merge a preset into current features. Preset values override; unset keys in preset leave current unchanged.
 */
export function applyPresetToFeatures(
  current: Record<PortalFeatureFlagKey, boolean>,
  preset: PortalFeaturePreset
): Record<PortalFeatureFlagKey, boolean> {
  return { ...current, ...preset } as Record<PortalFeatureFlagKey, boolean>;
}
